### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'padding_mode'

### ISSUE THREAD

**Issue by FLHonker** [yulu0724/EmbeddingDistillation#2]
AttributeError: 'Conv2d' object has no attribute 'padding_mode'
./run_main.sh: line 14: ./results/cub_triplet_resnet18_resnet101_relative_0.10_test.txt: No such file or directory
./run_main.sh: line 15: ./results/cub_triplet_resnet18_resnet101_relative_0.10_test.txt: No such file or directory

**Comment by yulu0724** [comment]
If you use the correct version of python, pytorch. The first problem should disappear.
You should make a folder 'results'.
