### ISSUE TITLE
batchsize=64 num_instance=4

### ISSUE THREAD

**Issue by zhanghanqi** [yulu0724/EmbeddingDistillation#5]
When batchsize=64 and num_instance=4,the code has the error RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB.But cuda has memory,I can't set up batchsize=128,num_instance=8.

**Comment by zhanghanqi** [comment]
I use batchsize=8 ,num_instances=4 and epochs=1600.The result is [0.55047265 0.68332208 0.79237002 0.8786293  0.93568535]  .The paper result is [58,69,79.4,87.8,93.6].

**Comment by yulu0724** [comment]
Hi, our results are reported with the setting batchsize=32 and num_instances=8, epoch=2000.  It is good to know with lower batch size and num_instances, the results are still reproducible. Thanks!
